---
title: "Andropogonae Terminal Velocity Stats"
author: "Lauren Sullivan"
date: 'Last updated: `r Sys.Date()`'
output:
  html_document:
    smart: no
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
rm(list = ls())
library(tidyverse)
library(cowplot)
library(readxl)
theme_set(theme_cowplot())
library(tidyverse)
```

## Terminal Velocity Analysis

Here we analyze the terminal velocity of 25 species within the Andropogonae to see if terminal velocity varies by species once we account for species relatedness.

```{r}
# PROLOG   ##############################################################################

# PROJECT: Andropogonae_dispersaltraits
# PURPOSE: How do dispersal traits differ across the Andropogonae
# AUTHOR:  Lauren Sullivan (llsull@msu.edu)
# COLLAB:  Toby Kellogg, Kurt Petersen, Binbin Wang, Huijie Wu
# CREATED: 8 Oct 2024
# LATEST:  8 Oct 2024
# NOTES:   
#
# FILES:   "terminal_velocity.csv" - tv and mass data for all dropped seeds
#
#
  

# PROLOG   ##############################################################################
```
